# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Ensure root composer is up-to-date
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    reviewers:
      - BitcoinMitchell
    labels:
      - dependencies

  # Ensure module composer is up-to-date
  - package-ecosystem: composer
    directory: /modules/cryptwerk
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    reviewers:
      - BitcoinMitchell
    labels:
      - dependencies

  # Ensure workflows are up-to-date
  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    reviewers:
      - BitcoinMitchell
    labels:
      - dependencies
