version: '3'
services:
  mariadb:
    container_name: prestashop_mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_SKIP_TEST_DB=yes
      - MARIADB_USER=prestashop
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=prestashop
    image: 'bitnami/mariadb:11.6'
    ports:
      - '3305:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  prestashop:
    container_name: prestashop_prestashop
    depends_on:
      - mariadb
      - btcpayserver
    environment:
      - PRESTASHOP_HOST=prestashop:8080
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=prestashop
      - PRESTASHOP_DATABASE_PASSWORD=bitnami
      - PRESTASHOP_DATABASE_NAME=prestashop
      - PRESTASHOP_EMAIL=user@example.com
      - PRESTASHOP_PASSWORD=bitnami1
    expose:
      - '8080'
      - '8443'
    image: 'bitnami/prestashop:8.1.7'
    links:
      - mariadb
      - btcpayserver
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - 'prestashop_data:/bitnami/prestashop'

  mailpit:
    container_name: prestashop_mailpit
    image: 'axllent/mailpit:latest'
    logging:
      driver: none
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mariadb_data: { driver: local }
  prestashop_data: { driver: local }
